services:
  - type: web
    name: laravel-api
    env: php
    plan: free
    rootDir: public
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://functionalfood.onrender.com
